compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU         # <- DDP
num_processes: 4                    # <- #GPUs / processes
gpu_ids: "0,1,2,3"
mixed_precision: 'bf16'
use_cpu: false
downcast_bf16: 'no'
rdzv_backend: 'c10d'
same_network: true
