compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU         # <- DDP
num_processes: 1                    # <- #GPUs / processes
mixed_precision: 'bf16'
use_cpu: false
downcast_bf16: 'no'
rdzv_backend: 'static'
same_network: true
