train_dataset:
  name: CINEFlowMatchLatentDataset
  args:
    root: /storage/CINE_data/latents_like_cine_no_empty_4   # where the new precompute wrote latents
    split: train      

val_dataset:
  name: CINEFlowMatchDataset           # unchanged raw-val path (uses VAE at val)
  args:
    root: /storage/CINE_data
    split: val
    normalize: qmag

dataloader:
  train_batch_size: 8     # each item yields a list of clips; we flatten across the batch
  val_batch_size: 1
  num_workers: 8
  pin_memory: false
  shuffle: true

# Frozen VAE (for latent space)
vae:
  import_path: CardiacVAE.model.vae   # python module containing CardiacVAE
  class_name: CardiacVAE
  args:
    in_channels: 2
    z_dim: 16
    dim: 256
    dim_mult: [1, 2] # [1, 2, 4] for 4x spatial downsampling, [1, 2] for 2x spatial downsampling
    num_res_blocks: 4
    attn_scales: []
  load_state_dict_from: '/storage/matt_models/cardiac_vae/videos/step_0195000/state.pt'
  strict_load: false
  resume: true

# FM transformer
model:
  import_path: CardiacFM.model.transformer
  class_name: LatentFlowMatchTransformer
  args:
    latent_channels: 16
    hidden_size: 1280
    depth: 40
    heads: 16
    mlp_ratio: 4.0
    patch_size: [1, 2, 2]   # latent tokens = n'*H'*W'
    rope_axes_dim: [12,34,34]
  load_state_dict_from: none
  strict_load: false
  resume: false

optim:
  lr: 0.0001
  betas: [0.9, 0.99]
  weight_decay: 0.01
  grad_clip: 1.0
  total_steps: 1000000
  ema_decay: 0.999
  scheduler:
    type: cosine
    eta_min_ratio: 0.1  # final lr = lr * eta_min_ratio

validation:
  patch_h: 80
  patch_w: 80
  patch_t: 7
  # spatial overlap between patches
  overlap_spatial_pct: 1.0   # e.g., 5.0 means 5% overlap

  # ---- DC guidance knobs ----
  dc_iters: 2                # K inner DC steps per sampler step
  dc_lambda: 0.3
  dc_step_scale: 15.0

  # microbatching controls
  dc_group_size: 0           # 0 or null => use ALL patches together (fastest, higher mem)
  # dc_group_size: 32        # example: process 32 patches at a time if memory is tight
  dc_decode_mb: 64           # VAE decode batch *inside DC* (independent of patch_batch)
  dc_decode_bs: 8

  # diagnostics
  debug_patch_placement: true

sampler:
  num_steps: 50
  variant: bh1
  shift: 3.0

logging:
  project: cardiac-lfm             # NEW
  run_name: wan_fm_videos          # NEW
  log_every_steps: 100
  val_every_steps: 20000
  save_every_steps: 20000
  out_dir: /storage/matt_models/latent_fm
  wandb_dir: /storage/matt_models/wandb   # NEW (optional)
  wandb_cache_dir: /storage/matt_models/wandbcache  # NEW (optional)

teacache:
  enable: false         # or false
  rel_l1_thresh: 0.14  # start around [0.10, 0.15], per your fit script’s printout
  poly_file: teacache_poly.json

deg:
  R: 2