train_dataset:
  name: CINEPixelDataset
  args:
    data_path: /users/PAS2812/mattbendel/CINE_data/train.pkl  # <- memory-mapped pickle
    t_frames: 8
    crop_hw: [64, 64]
    std_scale: 1.5
    apply_preproc: true
    log_stats: true

val_dataset:
  name: CINEPixelDataset
  args:
    data_path: /users/PAS2812/mattbendel/CINE_data/val.pkl
    t_frames: 8
    crop_hw: [64, 64]
    std_scale: 1.5
    apply_preproc: true
    log_stats: false

dataloader:
  train_batch_size: 4
  val_batch_size: 1
  num_workers: 8
  pin_memory: false
  shuffle: true

# Model is your pixel-space FM network
model:
  import_path: CardiacFM.model.transformer_pixel
  class_name: FlowMatchTransformer
  args:
    latent_channels: 2
    hidden_size: 864
    depth: 40
    heads: 12
    mlp_ratio: 4.0
    patch_size: [1, 2, 2]
    rope_axes_dim: [16, 28, 28]
  load_state_dict_from: none
  strict_load: false
  resume: false

optim:
  lr: 0.0002
  betas: [0.9, 0.99]
  weight_decay: 0.01
  grad_clip: 1.0
  total_steps: 500000
  ema_decay: 0.999
  accum_steps: 1
  scheduler:
    type: cosine
    eta_min_ratio: 0.1

validation:
  patch_h: 64
  patch_w: 64
  patch_t: 8
  overlap_spatial_pct: 1.0
  num_uncond_videos: 8
  latent_grid_fps: 7
  # For inverse/DC path (kept here for later use)
  dc_lambda: 0.3
  dc_every: 4
  dc_step_size: 5.0

sampler:
  num_steps: 50
  t_scale: 1000        # <-- kept at 1000 as requested
  # optional extras if you later add reparam variants
  sigma_exponent: 1.0

logging:
  project: cardiac-lfm
  run_name: fm_pixels_64x64x8
  log_every_steps: 100
  val_every_steps: 1000
  save_every_steps: 20000
  out_dir: /users/PAS2812/mattbendel/latent_fm
  wandb_dir: /users/PAS2812/mattbendel/wandb
  wandb_cache_dir: /users/PAS2812/mattbendel/wandbcache

deg:
  R: 8
