train_dataset:
  name: CINEFlowMatchLatentDataset
  args:
    root: /storage/CINE_data/latents   # NEW: where precompute wrote latents
    split: train
    num_time_samples: 1               # same sampling semantics as before
    patch_batch: 8

val_dataset:
  name: CINEFlowMatchDataset           # unchanged raw-val path (uses VAE at val)
  args:
    root: /storage/CINE_data
    split: val
    normalize: qmag

dataloader:
  train_batch_size: 1     # each item yields a list of clips; we flatten across the batch
  val_batch_size: 1
  num_workers: 8
  pin_memory: false
  shuffle: true

# Frozen VAE (for latent space)
vae:
  import_path: CardiacVAE.model.vae   # python module containing CardiacVAE
  class_name: CardiacVAE
  args:
    in_channels: 2
    z_dim: 16
    dim: 256
    dim_mult: [1, 2] # [1, 2, 4] for 4x spatial downsampling, [1, 2] for 2x spatial downsampling
    num_res_blocks: 4
    attn_scales: []
  load_state_dict_from: '/storage/matt_models/cardiac_vae/videos/step_0195000/state.pt'
  strict_load: false
  resume: false

# FM transformer
model:
  import_path: CardiacFM.model.transformer
  class_name: LatentFlowMatchTransformer
  args:
    latent_channels: 16
    hidden_size: 1392
    depth: 40
    heads: 24
    mlp_ratio: 4.0
    patch_size: [1, 2, 2]   # latent tokens = n'*H'*W'
  load_state_dict_from: none
  strict_load: false
  resume: false

optim:
  lr: 0.0002
  betas: [0.9, 0.99]
  weight_decay: 0.01
  grad_clip: 1.0
  total_steps: 400000
  ema_decay: 0.999
  scheduler:
    type: cosine
    eta_min_ratio: 0.1  # final lr = lr * eta_min_ratio

validation:
  patch_h: 80
  patch_w: 80
  patch_t: 7

sampler:
  num_steps: 50
  variant: bh1
  shift: 3.0

logging:
  project: cardiac-lfm             # NEW
  run_name: wan_fm_videos          # NEW
  log_every_steps: 100
  val_every_steps: 20000
  save_every_steps: 20000
  out_dir: /storage/matt_models/latent_fm
  wandb_dir: /storage/matt_models/wandb   # NEW (optional)
  wandb_cache_dir: /storage/matt_models/wandbcache  # NEW (optional)

teacache:
  enable: false         # or false
  rel_l1_thresh: 0.14  # start around [0.10, 0.15], per your fit script’s printout
  poly_file: teacache_poly.json
