# -----------------------------
# CardiacVAE training (stage-aware; step-based)
# -----------------------------

stages:
  mode: videos   # or videos

train_dataset:
  name: CINEDataset
  args:
    root: /storage/CINE_data
    split: train
    stage_mode: videos  # or videos
    fixed_train_L: 7
val_dataset:
  name: CINEDataset
  args:
    root: /storage/CINE_data
    split: val
    stage_mode: videos  # or videos
test_dataset:
  name: CINEDataset
  args:
    root: /storage/CINE_data
    split: test
    stage_mode: videos  # or videos
dataloader:
  train_batch_size: 2
  val_batch_size: 1
  num_workers: 16
  pin_memory: false
  shuffle: true

# Model
model:
  import_path: CardiacVAE.model.vae   # python module containing CardiacVAE
  class_name: CardiacVAE
  args:
    in_channels: 2
    z_dim: 16
    dim: 256
    dim_mult: [1, 2] # [1, 2, 4] for 4x spatial downsampling, [1, 2] for 2x spatial downsampling
    num_res_blocks: 4
    attn_scales: []
    dropout: 0.0
  load_state_dict_from: '/storage/matt_models/cardiac_vae/pretrain_2d/step_0065000/state.pt'
  strict_load: false
  resume: false

# Optimization (step-based)
optim:
  lr: 0.0002
  betas: [0.9, 0.99]
  weight_decay: 0.0
  grad_clip: 1.0
  total_steps: 200000
  accum_steps: 1
  scheduler:
    type: cosine
    eta_min_ratio: 0.1  # final lr = lr * eta_min_ratio

# Loss weights & schedules (per stage)
loss:
  pretrain_2d:
    complex_l1: true
    use_lpips: true
    w_l1: 3.0
    w_mse: 100.0
    w_lpips: 3.0
    w_kl: 3e-6
    w_ortho: 1e-6
    schedules:
      kl:     {type: linear, start_scale: 0.5, end_scale: 1.0, pct_of_steps: 0.2}
      ortho:  {type: linear, start_scale: 0.5, end_scale: 1.0, pct_of_steps: 0.6}
      lpips:  {type: cosine, start_scale: 0.5, end_scale: 1.0, pct_of_steps: 0.2}

  videos:
    complex_l1: true
    use_lpips: true
    lpips_frames: 'all'
    w_l1: 3.0
    w_mse: 100.0
    w_lpips: 3.0
    w_kl: 3e-5
    # w_tvz: 1e-4
    w_ortho: 1e-6
    w_tvz: 0.0
    schedules:
      kl:     {type: linear, start_scale: 0.5, end_scale: 1.0, pct_of_steps: 0.1}
      tvz:    {type: linear, start_scale: 0.2, end_scale: 1.0, pct_of_steps: 0.5}
      ortho:  {type: linear, start_scale: 0.0, end_scale: 1.0, pct_of_steps: 0.5}
      lpips:  {type: cosine, start_scale: 0.5, end_scale: 1.0, pct_of_steps: 0.2}

validation:
  patch_h: 80
  patch_w: 80
  patch_t: 9      # temporal size (videos). For pretrain_2d we use 1.
  patch_batch: 32  # how many patches to run through the VAE at once

# Logging / Validation / Checkpoints
logging:
  project: cardiac-vae
  run_name: wan_vae_complex_l1_lpips_kl_11x80x80_patches
  log_every_steps: 50
  val_every_steps: 5000
  save_every_steps: 5000
  val_num_batches: 20
  out_dir: /storage/matt_models/cardiac_vae
  wandb_dir: /storage/matt_models/wandb
  wandb_cache_dir: /storage/matt_models/wandbcache
